config/routes.rb
Rails.application.routes.draw do
  resources :vote_records
  resources :voters
  resources :polls

end

app/models/poll.rb
class Poll < ActiveRecord::Base
  belongs_to :poll
end

def self.open
    Polls.find(:all,
                  :conditions => ["start <= ? and end >= ?",
                                  Time.now, Time.now])
    if (votes_for_user = VoteRecord.find_all_by_voter_id voter_id) != nil
      done = Set.new
      votes_for_user.each { |v| done << v.poll_id }
      open.delete_if { |p| done.include? p.id }
    end
    open
  end

app/models/vote_record.rb
class VoteRecord < ActiveRecord::Base
belongs_to :voter
end
  def self.record_one_vote(poll, voter, vote_value)
    some_vote = find_by_poll_id_and_voter_id(question.id, voter.id)
    if some_vote == nil
      new_vote = VoteRecord.new
      new_vote.voter_id = voter.id
      new_vote.poll_id = poll.id
      #logger.log "Voter #{voter.id} answering #{vote_value} to question #{question.id}"
      if vote_value == "yes"
        new_vote.is_yes = 1
      elsif vote_value == "no"
        new_vote.is_yes = 0
        # otherwise, value is NULL (for abstention)
      end
      new_vote.save
    end
  end

  def self.record_votes(votes, voter)
    return if votes == nil
    votes.each do |q_id, vote_value|
      if (p = Poll.find(p_id)) != nil && vote_value != "no_vote"
        record_one_vote(p, voter, vote_value)
      end
    end
  end

app/models/voter.rb
class Voter < ActiveRecord::Base
    has_many :vote_record 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]

  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:body, :start, :end)
    end
end

app/controllers/vote_controller.rb
class VoteController < ApplicationController
    def list
        @polls =Poll.find (:all)  
    end 
    @uname = params [:unsername] |  
    pword  = params [:pword]
    voter_entry = @uname && Voter.find_by_username(@uname)
    if voter_entry == nil || voter_entry.password != pword
      # should post an error here
      render :action => "vote/index"  # redisplay login form
    else
        @polls = Polls.open 
    end 
    
end
def record_votes
    uname = params[:username]
    if (voter = Voter.find_by_username(uname)) == nil
      flash[:login_error] = "User id {uname} no longer valid - please log back in."
      render :action => "vote/index"
    else
      VoteRecord.record_votes(params[:poll], voter)
    end
  end
  @polls = Poll.open_polls_for(voter_entry.id)

app/controllers/vote_records_controller.rb
class VoteRecordsController < ApplicationController
  before_action :set_vote_record, only: [:show, :edit, :update, :destroy]

  # GET /vote_records
  # GET /vote_records.json
  def index
    @vote_records = VoteRecord.all
  end

  # GET /vote_records/1
  # GET /vote_records/1.json
  def show
  end

  # GET /vote_records/new
  def new
    @vote_record = VoteRecord.new
  end

  # GET /vote_records/1/edit
  def edit
  end

  # POST /vote_records
  # POST /vote_records.json
  def create
    @vote_record = VoteRecord.new(vote_record_params)

    respond_to do |format|
      if @vote_record.save
        format.html { redirect_to @vote_record, notice: 'Vote record was successfully created.' }
        format.json { render :show, status: :created, location: @vote_record }
      else
        format.html { render :new }
        format.json { render json: @vote_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vote_records/1
  # PATCH/PUT /vote_records/1.json
  def update
    respond_to do |format|
      if @vote_record.update(vote_record_params)
        format.html { redirect_to @vote_record, notice: 'Vote record was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote_record }
      else
        format.html { render :edit }
        format.json { render json: @vote_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vote_records/1
  # DELETE /vote_records/1.json
  def destroy
    @vote_record.destroy
    respond_to do |format|
      format.html { redirect_to vote_records_url, notice: 'Vote record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote_record
      @vote_record = VoteRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_record_params
      params.require(:vote_record).permit(:voter_id, :question_id, :is_yes)
    end
end

app/controllers/voters_controller.rb
class VotersController < ApplicationController
  before_action :set_voter, only: [:show, :edit, :update, :destroy]

  # GET /voters
  # GET /voters.json
  def index
    @voters = Voter.all
  end

  # GET /voters/1
  # GET /voters/1.json
  def show
  end

  # GET /voters/new
  def new
    @voter = Voter.new
  end

  # GET /voters/1/edit
  def edit
  end

  # POST /voters
  # POST /voters.json
  def create
    @voter = Voter.new(voter_params)

    respond_to do |format|
      if @voter.save
        format.html { redirect_to @voter, notice: 'Voter was successfully created.' }
        format.json { render :show, status: :created, location: @voter }
      else
        format.html { render :new }
        format.json { render json: @voter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /voters/1
  # PATCH/PUT /voters/1.json
  def update
    respond_to do |format|
      if @voter.update(voter_params)
        format.html { redirect_to @voter, notice: 'Voter was successfully updated.' }
        format.json { render :show, status: :ok, location: @voter }
      else
        format.html { render :edit }
        format.json { render json: @voter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voters/1
  # DELETE /voters/1.json
  def destroy
    @voter.destroy
    respond_to do |format|
      format.html { redirect_to voters_url, notice: 'Voter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voter
      @voter = Voter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def voter_params
      params.require(:voter).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/vote_helper.rb
module VoteHelper
end

app/helpers/vote_records_helper.rb
module VoteRecordsHelper
end

app/helpers/voters_helper.rb
module VotersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/polls/_form.html.erb
<%= form_for(@poll) do |f| %>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% @poll.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.datetime_select :start %>
  </div>
  <div class="field">
    <%= f.label :end %><br>
    <%= f.datetime_select :end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/polls/edit.html.erb
<h1>Editing Poll</h1>

<%= render 'form' %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

app/views/polls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Polls</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Start</th>
      <th>End</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= poll.body %></td>
        <td><%= poll.start %></td>
        <td><%= poll.end %></td>
        <td><%= link_to 'Show', poll %></td>
        <td><%= link_to 'Edit', edit_poll_path(poll) %></td>
        <td><%= link_to 'Destroy', poll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poll', new_poll_path %>

app/views/polls/new.html.erb
<h1>New Poll</h1>

<%= render 'form' %>

<%= link_to 'Back', polls_path %>

app/views/polls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @poll.body %>
</p>

<p>
  <strong>Start:</strong>
  <%= @poll.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @poll.end %>
</p>

<%= link_to 'Edit', edit_poll_path(@poll) %> |
<%= link_to 'Back', polls_path %>

app/views/vote/index.html.erb
<HTML>
<HEAD>
    <TITLE >VOTIGN REGISTRATION </TITLE>
</HEAD>
<BODY>
    <CENTRE>
        <H2>
            "ENTER USER ID AND PASSWORD TO VOTE "
        </H2>
    </CENTRE>
    </BODY>
<%= form_tag :action => 'list' do %>
<centre>
    <table>
        <tr><td>username :</td><td><%= text_field_tag :username %></td></tr>
        <tr><td>Password :</td><td><%= text_field_tag :pword %></td></tr>
    </table>
    <br/> 
    <%= submit_tag 'Login' %>
    </centre>
    
    <%=end%>
    
    </HTML>

app/views/vote/list.html.erb
<HTML>
<HEAD>
    <TITLE>"POLL LIST "</TITLE>
</HEAD>
</HTML>

<BODY>><CENTRE>
    <H2> <span id ="title"> PLACE YOUR VOTE HERE</span_id> </H2>
    
</CENTRE></BODY>
YOU CAN VOTE ON WHICHEVER ISSUES AND RETURN LATER TO VOTE ON SOME MORE 

 <%= form_tag :action => 'record_votes' do %>

  <%= hidden_field_tag(:username, @uname) %>

  <ol>
  <% for polls in @polls %>
    <p>
    <li><font size=+1><%= poll.body %>   
        <%= select "poll", poll.id,
                   [["Your vote?", :no_vote], ["Yes", :yes], ["No", :no],
                    ["Abstain", :abstain]] %>
        </font>
        <br />
        <font size=-1>(Vote due by: <%= poll.end %>)</font>
    </li>
  <% end %>
  </ol>

  <b />

  <center>
  <p>
  <%= submit_tag "Place Vote(s)" %>
  </center>

  <% end %>

  </BODY>
  </HTML>

app/views/vote/record_votes.html.erb
  <HTML>
  <HEAD>
  <TITLE>Done Voting</TITLE>
  </HEAD>

  <BODY>
  <center>
  <h2>Thanks!</h2>
  </center>

  Thank you for voting.  You can click <a href="./">here</a> to vote on
  additional questions (if there are any).

  </BODY>
  </HTML>

app/views/vote_records/_form.html.erb
<%= form_for(@vote_record) do |f| %>
  <% if @vote_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote_record.errors.count, "error") %> prohibited this vote_record from being saved:</h2>

      <ul>
      <% @vote_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :voter_id %><br>
    <%= f.number_field :voter_id %>
  </div>
  <div class="field">
    <%= f.label :question_id %><br>
    <%= f.number_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :is_yes %><br>
    <%= f.check_box :is_yes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vote_records/edit.html.erb
<h1>Editing Vote Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote_record %> |
<%= link_to 'Back', vote_records_path %>

app/views/vote_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vote Records</h1>

<table>
  <thead>
    <tr>
      <th>Voter</th>
      <th>Question</th>
      <th>Is yes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vote_records.each do |vote_record| %>
      <tr>
        <td><%= vote_record.voter_id %></td>
        <td><%= vote_record.question_id %></td>
        <td><%= vote_record.is_yes %></td>
        <td><%= link_to 'Show', vote_record %></td>
        <td><%= link_to 'Edit', edit_vote_record_path(vote_record) %></td>
        <td><%= link_to 'Destroy', vote_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote record', new_vote_record_path %>

app/views/vote_records/new.html.erb
<h1>New Vote Record</h1>

<%= render 'form' %>

<%= link_to 'Back', vote_records_path %>

app/views/vote_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Voter:</strong>
  <%= @vote_record.voter_id %>
</p>

<p>
  <strong>Question:</strong>
  <%= @vote_record.question_id %>
</p>

<p>
  <strong>Is yes:</strong>
  <%= @vote_record.is_yes %>
</p>

<%= link_to 'Edit', edit_vote_record_path(@vote_record) %> |
<%= link_to 'Back', vote_records_path %>

app/views/voters/_form.html.erb
<%= form_for(@voter) do |f| %>
  <% if @voter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voter.errors.count, "error") %> prohibited this voter from being saved:</h2>

      <ul>
      <% @voter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/voters/edit.html.erb
<h1>Editing Voter</h1>

<%= render 'form' %>

<%= link_to 'Show', @voter %> |
<%= link_to 'Back', voters_path %>

app/views/voters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Voters</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @voters.each do |voter| %>
      <tr>
        <td><%= voter.username %></td>
        <td><%= voter.password %></td>
        <td><%= link_to 'Show', voter %></td>
        <td><%= link_to 'Edit', edit_voter_path(voter) %></td>
        <td><%= link_to 'Destroy', voter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Voter', new_voter_path %>

app/views/voters/new.html.erb
<h1>New Voter</h1>

<%= render 'form' %>

<%= link_to 'Back', voters_path %>

app/views/voters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @voter.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @voter.password %>
</p>

<%= link_to 'Edit', edit_voter_path(@voter) %> |
<%= link_to 'Back', voters_path %>